### ISSUE TITLE
Bridging issues

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig#22]
Trying different combinations with bridges yelds very strange (and wrong) results.

Generation of bridged interfaces must be improved.

- [x] the whole ``__find_bridges`` idea is quite a bad one. It would be better to remove that code altoghether and find a simpler solution.
- [x] bridges should be defined only in ``/etc/config/network``.
- [x] in ``/etc/config/wireless`` the attached networks can be defined with a custom attribute, like ``networks``.
- [x] the bridge schema should require the presence of ``bridge_members``

**Comment by riblo** [comment]
trying to define a bridge interface without specifying "bridge_members" raises this exception:

```
Traceback (most recent call last):
  File "/Users/Riccardo/.virtualenvs/netjsonconfig/bin/netjsonconfig", line 10, in <module>
    execfile(__file__)
  File "/Users/Riccardo/Work/netjsonconfig/bin/netjsonconfig", line 93, in <module>
    output = getattr(instance, args.method)()
  File "/Users/Riccardo/Work/netjsonconfig/netjsonconfig/backends/openwrt/openwrt.py", line 75, in render
    additional_output = renderer.render()
  File "/Users/Riccardo/Work/netjsonconfig/netjsonconfig/backends/base.py", line 43, in render
    context = self.get_context()
  File "/Users/Riccardo/Work/netjsonconfig/netjsonconfig/backends/base.py", line 57, in get_context
    context[key] = getattr(self, method)()
  File "/Users/Riccardo/Work/netjsonconfig/netjsonconfig/backends/openwrt/renderers.py", line 34, in _get_interfaces
    bridge_members = ' '.join(interface['bridge_members'])
KeyError: 'bridge_members'
```
